FROM oven/bun:1 AS build

WORKDIR /build

COPY constants.json .
COPY web/ web/

WORKDIR /build/web
RUN bun ci
RUN bun run build

FROM caddy:2-alpine AS runtime
COPY Caddyfile /etc/caddy/Caddyfile
COPY --from=build /build/web/dist /srv
EXPOSE 80
